version: '3'

services:

  mongo1:
    image: mongo
    container_name: mongo1
    command: "--bind_ip_all --replSet rs0"

  mongo2:
    image: mongo
    container_name: mongo2
    command: "--bind_ip_all --replSet rs0"

  replica:
    container_name: replica
    build:
      context: .
      dockerfile: ./Dockerfile
    image: replica
    command: "--mongourl1=mongo1 --mongourl2=mongo2"
    depends_on: 
      - mongo1
      - mongo2
    restart: always

  client1:
    container_name: client1
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: client
    command: "--mongourl=mongo1"
    depends_on: 
      - mongo1
    restart: always

  client2:
    container_name: client2
    build:
      context: .
      dockerfile: ./client/Dockerfile
    image: client
    command: "--mongourl=mongo2"
    depends_on: 
      - mongo2
    restart: always

