version: '3'

services:

  mongo1:
    image: mongo
    container_name: mongo1
    command: "--bind_ip_all --replSet rs0"

  mongo2:
    image: mongo
    container_name: mongo2
    command: "--bind_ip_all --replSet rs0"

  replica:
    ontainer_name: replica
    build:
      context: .
      dockerfile: ./Dockerfile
    image: replica
    command: "--mongourl1=mongo1 --mongourl2=mongo2"
    depends_on: 
      - mongo1
      - mongo2
    restart: always

