version: '3'

services:

  mongo1:
    image: mongo
    networks:
      - db

  replica:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: replica
    command: --mongourl=mongo1
    depends_on: 
      - mongo1
    networks:
      - db
    restart: always

networks:
  db: